name: Build and Deploy Website

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the main branch (adjust as needed)
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch (optional)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version for your environment

    - name: Install dependencies
      run: |
        pip install jupyter  # Install any dependencies you need (e.g., jupyter, pandas, etc.)
        pip install -r requirements.txt  # If you have a requirements.txt

    - name: Generate Website (example with Jupyter)
      run: |
        jupyter nbconvert --to html my_notebook.ipynb  # Convert Jupyter notebook to HTML (adjust as necessary)
        # Alternatively, use a static site generator like Jekyll or Hugo here

    - name: Build static assets (if needed)
      run: |
        # Run build commands if necessary (e.g., for static site generators)
        # For example: bundle exec jekyll build or hugo --minify

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages  # The branch to deploy to (can be 'main' for GitHub Pages)
        folder: _site  # The folder where the built site is located (adjust as needed)
        token: ${{ secrets.GITHUB_TOKEN }}  # Token for GitHub authentication
