name: Deploy Website

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch where your website files will be deployed
          folder: _html  # The folder containing your HTML files
          target-folder: /  # Root of your gh-pages branch

      # Deploy CSS files (optional step if your CSS is separate)
      - name: Deploy CSS Files
        run: |
          cp -r _css/* ./gh-pages/  

      # Commit changes to the gh-pages branch
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy website updates"
          git push origin gh-pages
