name: Deploy Website

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git for deployment
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Check for changes and deploy
      run: |
        # Check if there are any changes to commit
        git diff --exit-code || (git add -A && git commit -m "Automated deployment" && git push origin main:gh-pages)
